# Generated by Django 2.1.7 on 2019-08-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocao', '0003_auto_20190705_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='foto',
            field=models.URLField(default=0, help_text='Informe a URL de uma imagem para este animal. Ex: http://...'),
            preserve_default=False,
        ),
    ]
